export const FadConstants = Object.freeze({
  buttons: {
    search: 'Search'
  },

  elementRef: {
    fadSearchListMapContent: 'fad-search-list-map-content'
  },

  text: {
    landingPageTitle: 'Find a Doctor and Get Cost Estimates',
    landingPage_entity_placeHolder: 'Doctor Name, procedure, hospital, facility',
    landingPage_location_placeHolder: 'Zip code or city, state',
    landingPage_selectPlan_placeHolder: 'Select a plan',
    type: 'type',
    medicalIndexToHomeNavWarning: 'navigating from medical-index page to landing page',
    backSearchResults: 'Back to search results',
    specialities: 'Specialities',
    inNetwork: 'In-Network',
    acceptingNewPatients: 'Accepting New Patients',
    boardCertified: 'Board Certified',
    rating: 'Rating',
    languageSpokenProfessionalStaff: 'Language spoken by Professional or Staff',
    serviceAvailableLocation: 'Service available at location',
    remove: 'Remove',
    numberOfAwards: 'Number of Awards',
    blueDistinction: 'Blue Distinction',
    recommendToFriend: 'Would recommend to a friend',
    costBreakdown: 'Cost Breakdown',
    chart1: 'Chart1',
    chart2: 'Chart2',
    chart1HeaderText: 'Overall Deductible',
    chart1Param1Text: 'Spend',
    chart1Param2Text: 'Remaining',
    chart1Param3Text: 'This procedure',
    chart2HeaderText: 'Out-Of-Pocket Maximum Usage',
    chart2Param1Text: 'Spend',
    chart2Param2Text: 'Remaining',
    chart2BarColor: '#8FBE48',
    chart2BarColorRemaining: '#ade5ad',
    outPocketMaximumCoinsurance: '* Out-of-Pocket Maximum = Coinsurance',
    myCost: 'my cost',
    insuranceCost: 'insurance cost',
    totalCost: 'total cost',
    breakdownForMyCost: 'Breakdown for my cost',
    coinsuranceResponsibility: 'co-insurance responsibility',
    towardsDeductible: 'towards deductible',
    coPay: 'copay',
    dontSeePlan: 'Don\'t know or see your plan?',
    dontKnowPlan: 'I don\'t know my plan'
  },

  components: {
    fadBaseSearchComponent: 'FadBaseSearchComponent',
    fadDoctorProfileComponent: 'FadDoctorProfileComponent',
    fadFacilityProfileComponent: 'FadFacilityProfileComponent',
    fadLandingPageComponent: 'FadLandingPageComponent',
    fadMedicalIndexComponent: 'FadMedicalIndexComponent',
    fadNoDocsPageComponent: 'FadNoDocsPageComponent',
    fadProfileCardComponent: 'FadProfileCardComponent',
    fadSearchFilterComponent: 'FadSearchFilterComponent',
    fadSearchListComponent: 'FadSearchListComponent',
    fadSearchResultsComponent: 'FadSearchResultsComponent',
    fadCompareTableComponent: 'FadCompareTableComponent',
    fadFacilityCompareComponent: 'fadFacilityCompareComponent',
    fadCostBreakdownComponent: 'fadCostBreakdownComponent',
  },

  errorMessages: {
    invalidServiceResponseData: 'Invalid Service Response Data',
    invalidZipSearch: 'Please enter Zip Code or City, State.',
    zipNoMatch: 'Please check that you have entered the correct Zip Code or City.',
  },

  labels: {

  },

  messages: {

  },

  methods: {
    openProfile: 'openProfile',
    onSearchListComponentInteraction: 'onSearchListComponentInteraction',
    onLandingPageSearchComponentInteraction: 'onLandingPageSearchComponentInteraction',
    onSelectionChange: 'onSelectionChange',
    fetchPopupContent: 'fetchPopupContent',
    addMarkers: 'addMarkers',
    onTabSelectionChange: 'onTabSelectionChange',
    getFadProfileSearchResults: 'getFadProfileSearchResults',
    doSearch: 'doSearch',
    clearTargetValue: 'clearTargetValue',
    redirectRequestPlanDropDown: 'redirectRequestPlanDropDown',
    redirectToLogin: 'redirectToLogin',
    displayZipCodeDropDown: 'displayZipCodeDropDown',
    displaySearchTextAutoCompleteDropDown: 'displaySearchTextAutoCompleteDropDown',
    hiddenSearchTextAutoCompleteDropDown: 'hiddenSearchTextAutoCompleteDropDown',
    hiddenPlanDropDown: 'hiddenPlanDropDown',
    hiddenZipCodeDropDown: 'hiddenZipCodeDropDown',
    checkAndDisplayPlanDropDown: 'checkAndDisplayPlanDropDown',
    checkAndDisplayPastSearchHistory: 'checkAndDisplayPastSearchHistory',
    checkAndDisplayDependentListDropDown: 'checkAndDisplayDependentListDropDown',
    checkAndDisplayZipCodeDropDown: 'checkAndDisplayZipCodeDropDown',
    createInteractiveMap: 'createInteractiveMap',
    createSearchCriteria: 'createSearchCriteria',
    displayDependentListDropDown: 'displayDependentListDropDown',
    displayPastSearchHistory: 'displayPastSearchHistory',
    displayPastSearchHistoryDropDown: 'displayPastSearchHistoryDropDown',
    displayPlanDropDown: 'displayPlanDropDown',
    fetchMedicalIndex: 'fetchMedicalIndex',
    filterAutoCompleteSearchOptions: 'filterAutoCompleteSearchOptions',
    getLocationInfo: 'getLocationInfo',
    getPlanNameList: 'getPlanNameList',
    goToBaseSearchPage: 'goToBaseSearchPage',
    getVitalsZipCodeInfo: 'getVitalsZipCodeInfo',
    getLocationFromLatLong: 'getLocationFromLatLong',
    geoLocationMethod: 'geoLocationMethod',
    initData: 'initData',
    ngOnChanges: 'ngOnChanges',
    ngOnInit: 'ngOnInit',
    onListItemClicked: 'onListItemClicked',
    openMedicalIndex: 'openMedicalIndex',
    openSelectionList: 'openSelectionList',
    populateSearchFields: 'populateSearchFields',
    showDoctorList: 'showDoctorList',
    valueChanges: 'valueChanges',
    getVitalsPlanInfo: 'getVitalsPlanInfo',
    getVitalsAutoCompleteSearchResponse: 'getVitalsAutoCompleteSearchResponse',
    getCompareTableDetail: 'getCompareTableDetail',
    costBreakdownAsLineChartOptions: 'costBreakdownAsLineChartOptions',
    selectAutoCompleteSearchTextOption: 'selectAutoCompleteSearchTextOption',
    getDoctorProfileDetails: 'getDoctorProfileDetails',
    getFacilityProfileDetails: 'getFacilityProfileDetails',
    searchTypeOptLableClickHandler: 'searchTypeOptLableClickHandler',
    getCostBreakDownData: 'getCostBreakDownData',
  },

  services: {
    fadBaseSearchService: 'FadBaseSearchService',
    fadDoctorProfileService: 'FadDoctorProfileService',
    fadFacilityProfileService: 'FadFacilityProfileService',
    fadFacilitySearchResultsService: 'FadFacilitySearchResultsService',
    fadLandingPageService: 'FadLandingPageService',
    fadMapSearchService: 'FadMapSearchService',
    fadMedicalIndexService: 'FadMedicalIndexService',
    fadNoDocsPageService: 'FadNoDocsPageService',
    fadSearchFilterService: 'FadSearchFilterService',
    fadSearchListService: 'FadSearchListService',
    fadDoctorProfileDetailService: 'FadDoctorProfileDetailService',
    fadFacilityProfileDetailService: 'FadFacilityProfileDetailService',
    fadSearchResultsService: 'FadSearchResultsService',
    fadService: 'FadService',
    landingPageService: 'landingPageService',
    searchTypeAheadControl_valueChanges: 'searchTypeAheadControl_valueChanges',
    planControl_valueChanges: 'planControl_valueChanges',
    fadCompareTableService: 'FadCompareTableService',
    fadFacilityCompareService: 'fadFacilityCompareService',
    fadCostBreakDownService: 'FadCostBreakdownService',
  },

  urls: {
    fadLandingPage: '/fad',
    fadLandingPageSearchAutocompleteListUrl: '/autocomplete/search',
    fadLandingPageProfessionalsSearchListUrl: '/professional/search',
    fadLandingPagePlansAutocompleteListUrl: '/plans',
    fadLandingPageZipcodeAutocompleteListUrl: '/cities',
    fadSearchHistoryUrl: '/recent/searches',
    fadVitalsSpecialitiesUrl: '/specialities/search',
    fadSearchResultsPage: '/fad/search-results',
    fadPastSearchQueries: '/fad/past-search-queries',
    fadCompareTablePage: '/fad/compare-table',
    fadFacilityCompareUrl: '/fad/facility-compare',
    fadGetDoctorProfile: '/web/vitals/v1/doctorprofile/getDoctorProfile',
    fadGetFacilityProfile: '/web/vitals/v1/doctorprofile/getFacilityProfile',
    fadDoctorProfilePage: '/fad/doctor-profile',
    fadFacilityProfilePage: '/fad/facility-profile',
    fadCostBreakDownUrl: '/fad/cost-breakdown',
    fadGetprofessionalprofile:'/getprofessionalprofile'
  },

  jsonurls: {
    fadLandingPage: '/fad',
    fadLandingPageSearchAutocompleteListUrl: '/assets/data/fad/vitals_autoComplete_Search.json',
    fadLandingPageProfessionalsSearchListUrl: '/assets/data/fad/vitals_professional_search_MultipleOuput.json',
    fadLandingPagePlansAutocompleteListUrl: '/assets/data/fad/vitals_plans.json',
    fadLandingPageZipcodeAutocompleteListUrl: '/assets/data/fad/vitals_cities.json',
    fadSearchHistoryUrl: '/assets/data/fad/vitals_past_10_searches.json',
    fadVitalsSpecialitiesUrl: '/assets/data/fad/vitals_specialities_search.json',
    fadSearchResultsPage: '/fad/search-results',
    fadPastSearchQueries: '/fad/past-search-queries',
    fadCompareTableUrl: '/assets/data/fad/compare_table_doctor.json',
    fadFacilityCompareUrl: '/assets/data/fad/facility-compare.json',
    fadGetDoctorProfile: '/assets/data/fad/doctor_profile_sample.json',
    fadGetFacilityProfile: '/assets/data/fad/facility_profile_sample.json',
    fadDoctorProfilePage: '/fad/doctor-profile',
    fadCostBreakDownUrl: '/assets/data/fad/doctor_profile_sample.json',
  },

  api: {
    switchToApiUrlFromJsonFile: false,
    fadUrl: 'https://myblueapi.us-east-1.elasticbeanstalk.com/myBlue/vitals',
    fadSwaggerBaseUrl : 'https://virtserver.swaggerhub.com/Bcb/professionalProfile/1.0.0'
  },


  leafLetAccessToken: 'pk.eyJ1Ijoib3ppbmlzbGUiLCJhIjoiY2ppYWJoaGR3MHp3ZTNxa3p3dnNnM2NiaCJ9.6k4AQo0CenMExQL9iObioQ',
  leafLetGeoCodingQueryTypes: ['postcode', 'place', 'region'],
  defaultZipCode: '02169',
  defaultCity: 'Quincy',
  defaultState: 'MA',
  defaultNetwork: 311005011,
  defaultGeoLocation : "42.242921,-71.009972",
  
  ProfessionalCode: 'P',
  FacilityCode: 'F',

  professionalSearchLimit: 10,
  professionalSearchRadius: 25,
  facilitySearchLimit: 10,
  facilitySearchRadius: 25,

  allProfessionalText: 'All doctors with',
  allFacilityText: 'All hospitals/facilities with',
  allProcedureText: 'All procedures with',
  areYouLookingFor: 'Are you looking for?',

  plans: {
    myCurrentPlanOption: 'my-current-plan-option',
    dontKnowPlanOption: 'dont-know-plan-option',
    defaultOption: 'default-option'
  },

  acceptingNewPatients: 'Accepting new patients',
  techSavvy: 'Tech Savvy Office',
  inNetworkOnly: 'In-Network Only',

  defaultSort: 'Distance'

});

